BaseURL = "http://example.org/"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "Hugo Authors"
title = "theATL Community"
theme = "hugo-vitae"
paginate = 5
enableRobotsTXT = true

copyright = "License: [CC-BY-SA-4.0](http://creativecommons.org/licenses/by-sa/4.0/)"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
	# Enable dark mode as default
	#darkmode = true

	# Use homepage.md instead of a list of posts
	homepage = true

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = []

	# Add meta description in head part
	description = "Community blog for theATL.social"

	# Add pagetitle to homepage <title> tag
	pagetitle = "New for theATL.social community"

	# Add a subtitle to your website
	subtitle = "Community blog for [theATL.social](https://theatl.social)"

	# Optional favicons for website
	#favicon = true

	# Add list of sections that should show up on the homepage
	mainSections = ["post"]

	# Add list of Sections/Types that should not be considered by RSS
	#nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Custom CSS applied to default styles. (Path could be "static/css/")
	#customcss = "css/custom.css"

	# Show reading time on a post
	readingTime = true

	# Show word count on a post
	wordCount = false

	# Show author on a post (groups with readingTime and wordCount)
	hideAuthor = false

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 4

#[[menu.main]]
#name = "Categories"
#url = "/categories"
#weight = 5

# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/theatl-social"

[[params.social]]
name = "Mastodon"
icon = "fab fa-mastodon"
url = "https://theatl.social/@admin"
